bookings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User, Group
from rest_framework import routers, serializers, viewsets, permissions

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']
# Group serializers
class GroupSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Group
        fields = ['url', 'name']

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)


urlpatterns = [
    path('bookings-admin/', admin.site.urls),
    path('', include(('users.urls', 'user'), namespace='user')),
    path('customer/', include('customers.urls')),
    path('job/', include(('jobs.urls', 'job'), namespace='job')),
    path('bookings-api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

customers/urls.py
from django.urls import path
from . import views

APP_NAME = "login"
urlpatterns = [
    # path('login', views.UserLogin, name="login"),
    # path('logout', views.UserLogout, name="logout"),
]

jobs/urls.py
from django.urls import path
from . import views

APP_NAME = "job"
urlpatterns = [
    path('book/', views.job_list, name="list"),
    path('book/add/', views.add_booking, name="add"),
]

users/urls.py
from django.urls import path
from . import views

APP_NAME = "user"
urlpatterns = [
	path('', views.user_home, name="home"),
	path('<int:pk>', views.user_profile, name="profile"),
	path('register/', views.register_user, name="register"),
	path('login/', views.user_login, name="login"),
	path('logout/', views.user_logout, name="logout"),
	path('tech/', views.technician_list, name="list"),
]

customers/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Customer(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	address = models.CharField(max_length=200)
	# contact_number = models.IntegerField()
	def __str__(self):
		return self.user.get_username().upper()

jobs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class JobBooking(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	tech = models.ForeignKey(User, on_delete=models.CASCADE, related_name="technician")
	note_to_tech = models.TextField()
	date = models.DateField()
	time = models.TimeField()
	timestamp = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	service = models.TextField()
	contact = models.CharField(max_length=13)
	done = models.BooleanField(default=False)
	cancel = models.BooleanField(default=False)
	def __str__(self):
		return self.tech.get_short_name().title()

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category_name = models.CharField(max_length=200)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.category_name
    class Meta:
        verbose_name_plural = 'categories'
class Handyman(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    members = models.ManyToManyField(User, through="TechMembership")
    def __str__(self):
        return self.category.category_name
    class Meta:
        verbose_name_plural = 'handymen'
class TechMembership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    handyman = models.ForeignKey(Handyman, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.handyman.category.category_name
    class Meta:
        verbose_name_plural = 'technician memberships'

jobs/forms.py
from django import forms
from .models import JobBooking
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from bootstrap_datepicker_plus import DateTimePickerInput, DatePickerInput, TimePickerInput

class AddBookingForm(forms.ModelForm):
	class Meta:
		model = JobBooking
		fields = [
			"tech",
			"note_to_tech",
			"date",
			"time",
			"service",
			"contact",
		]
		widgets = {
			'date': DatePickerInput(),
			'time': TimePickerInput(),
		}
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.form_method = 'post' # get or post
		self.helper.add_input(Submit('submit', 'Add Book')) 

users/forms.py
from django import forms
from django.contrib.auth.models import User

class RegisterUserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = [
			"email",
			"username",
			"password",
			"first_name",
			"last_name",
		]

customers/views.py
from django.shortcuts import render
from .models import Customer
# Create your views here.
def customer_profile(request):
	customer = Customer.objects.all()
	print(request.id)

jobs/views.py
from django.shortcuts import render, redirect
from .forms import AddBookingForm
from .models import JobBooking
# Create your views here.
def job_list(request):
    booking = JobBooking.objects.all()
    context = {
        'title': 'booking list',
        'booking': booking,
    }
    return render(request, "jobs/booking_list.html", context)
def add_booking(request):
    if request.method == 'POST':
        form = AddBookingForm(
            request.POST or None, 
            request.FILES or None,
            )
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect('job:list')
    else:
        form = AddBookingForm()
    context = {
        "form": form,
        "title": "book form",
    }
    return render(request, "jobs/job_booking.html", context)

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.conf import settings
from .forms import RegisterUserForm
from .models import Handyman, Category
# Create your views here.
def user_home(request):
	# user = get_object_or_404(User, pk=pk)
	context = {
		"title": "User",
		# "instance": user,
	}
	return render(request, "users/user_home.html", context)

def user_profile(request, pk):
	user = get_object_or_404(User, pk=pk)
	context = {
		"title": "User",
		"instance": user,
	}
	return render(request, "users/user_profile.html", context)

def register_user(request):
	if request.method == 'POST':
		form = RegisterUserForm(
			request.POST or None, 
			request.FILES or None,
			)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.is_staff = True
			instance.save()
			return redirect('user:login')
	else:
		form = RegisterUserForm()
	context = {
		"form": form,
		"title": "registration form",
	}
	return render(request, "users/register_user.html", context)
def technician_list(request):
	tech = Handyman.objects.all()
	context = {
		'title': "tech list",
		'tech': tech,
	}
	return render(request, "users/user_home.html", context)
# def user_setting(request, pk):
# 	if request.method == 'POST':
# 		form = UserSettingsForm(
# 			request.POST or None,
# 			request.FILES or None,
# 			)
# 		if form.is_valid():
# 			instance = form.save(commit=False)
# 			instance.
def user_login(request):
	next = request.GET.get('next', '/')
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user=authenticate(username=username, password=password)

		if user is not None:
			if user.is_active:
				login(request, user)
				return HttpResponseRedirect(next)
			else:
				HttpResponse("Inactive user")
		else:
			return HttpResponseRedirect(settings.LOGIN_URL)
	return render(request, "users/user_login.html", {"redirect_to": next, "title": "Login"})

def user_logout(request):
	logout(request)
	return HttpResponseRedirect(settings.LOGIN_URL)

templates/base.html
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <title>Hello, world!</title>
  </head>
  <body>
  	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  		<div class="container">
  			<a class="navbar-brand" href="{% url 'user:home' %}">BooKings</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
		      {% if request.user.is_authenticated %}
		      <li class="nav-item">
		      	<a class="nav-link" href="{% url 'user:profile' pk=request.user.id %}">Profile</a>
		      </li>
		      <li class="nav-item">
		      	<a class="nav-link" href="{%url 'job:list'%}">Book</a>
		      </li>
		      <li class="nav-item">
		      	<a class="nav-link" href="#">Request</a>
		      </li>
		      <li class="nav-item">
		      	<a class="nav-link" href="#">Apply as Technician</a>
		      </li>
		      {% else %}
		      <li class="nav-item">
		      	<a class="nav-link" href="{% url 'user:register' %}">Register</a>
		      </li>
		      {% endif %}
		    </ul>
		    <ul class="navbar-nav mr-rigth">
		      {% if request.user.is_authenticated %}
			  <li class="nav-item">
				<a class="nav-link" href="#settings">My Account</a>
			  </li>
		      <li class="nav-item">
		      	<a class="nav-link" href="{% url 'user:logout' %}">Logout <span class="fas fa-sign-out-alt"></span></a>
		      </li>
		      {% endif %}
		      {% if request.user.is_anonymous %}
		      <li class="nav-item">
		      	<a class="nav-link" href="{% url 'user:login' %}">Login</a>
		      </li>
		      {% endif %}
		    </ul>
		  </div>
  		</div>
	</nav>
    <!-- <h1>Hello, world!</h1> -->
    <div class="container" style="margin-top: 40px;">
    	{% block content %}
    	{% endblock %}
    </div>
    <div class="container">
    	<div class="row" style="margin-top: 80px;">
    		<div class="col-sm-4 offset-sm-4">
    			{% block login %}
    			{% endblock %}
    		</div>
    	</div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
	<script>
		$(document).ready( function () {
			$('#myTable').DataTable();
		} );
		// $('.dropdown').click(function(){
		// 	$('.dropdown-menu').toggleClass('show');
		// });
	</script>
	<!-- <script>
		// Add the following code if you want the name of the file appear on select
		$(".custom-file-input").on("change", function() {
		  var fileName = $(this).val().split("\\").pop();
		  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
		});
	</script> -->
  </body>
</html>

templates/customers/customer_profile.html
{% extends "base.html" %}

{% block content %}
{{}}
{% endblock %}

templates/jobs/booking_list.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron text-center">
  <h1 class="display-4">Home service for your home repair needs.</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{% url 'job:add' %}" role="button">Book now!</a>
  </p>
<!-- </div>
<hr>
<a href="{% url 'job:add' %}" class="btn btn-primary btn-sm">Book</a><br>
<hr>
<div class="row">
  <div class="col-sm-12">
    {% for b in booking %}
    <div class="card">
      <div class="card-header">
        Featured
      </div>
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
    <br>
    {% endfor %}
  </div>
</div> -->
{% endblock %}

templates/jobs/job_booking.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{form.media}}

{% block content %}
<div class="row">
	<div class="col-sm-4 offset-sm-4">
		<form action="" method="post">
			{% csrf_token %}
			<h3>{{title|title}}</h3>
			{% crispy form %}
			<!-- <input type="submit" value="Book" class="btn btn-primary btn-block"> -->
			<hr>
		</form>
	</div>
</div>
{% endblock %}

templates/users/register_user.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
	<div class="col-sm-4 offset-sm-4">
		<form action=".?next={{ redirect_to }}" method="post">
			{% csrf_token %}
			<h3>{{title|title}}</h3>
			{{form|crispy}}
			<input type="submit" value="Register" class="btn btn-primary btn-block">
			<hr>
		</form>
	</div>
</div>
{% endblock %}

templates/users/user_home.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4">BooKings</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.
  </p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Book now!</a>
  </p>
</div>
<h3>tech list</h3>
{% for t in tech %}
  <h3>{{ t.category.category_name }}</h3>
  {% for n in t.members.all %}
    {{ n }} <br>
    {% for i in n.techmembership_set.all %}
      {{ i.timestamp|date }} <br>
    {% endfor %}
  {% endfor %}
{% endfor %}
<!-- {{ tech }} -->
{% endblock %}

templates/users/user_login.html
{% extends "base.html" %}

{% block login %}
<h3>Login</h3>
<hr>  
<form action=".?next={{ redirect_to }}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">Username</label>
    <input name="username" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Username" required="required">
    <small id="emailHelp" class="form-text text-muted">We'll never share your username with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required="required">
  </div>
<!--   <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div> -->
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

templates/users/user_profile.html
{% extends "base.html" %}

{% block content %}
ID: {{instance.id}} <br>	
First Name: {{instance.first_name.upper}} <br>
Last Name: {{instance.last_name.upper}} <br>	
{% endblock %}